# -*- coding: utf-8 -*-
"""transformin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEjo0QswdTL799lQhGiQIS8XfP0HQb7l
"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torch import nn
import torch.nn.functional as F

transform = transforms.Compose([
    transforms.ToTensor(),
])

train_dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
test_dataset  = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader  = DataLoader(test_dataset, batch_size=64)

print("MNIST cargado correctamente")

class SimpleTransformerOCR(nn.Module):
    def __init__(self, d_model=64, nhead=4, num_layers=2):
        super().__init__()
        self.embedding = nn.Linear(28, d_model)  # cada fila es un token
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead)
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.classifier = nn.Linear(d_model, 10)

    def forward(self, x):
        # x: (B, 1, 28, 28)
        x = x.squeeze(1)            # (B, 28, 28)
        x = self.embedding(x)       # (B, 28, d_model)
        x = x.transpose(0, 1)       # (28, B, d_model) → formato Transformer
        h = self.encoder(x)         # (28, B, d_model)
        h_cls = h[0]                # primera fila como "token CLS"
        out = self.classifier(h_cls)
        return out

device = "cuda" if torch.cuda.is_available() else "cpu"

model = SimpleTransformerOCR().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(10):
    for i, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)

        logits = model(images)
        loss = criterion(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if i % 200 == 0:
            print(f"Epoch {epoch}, step {i}, loss {loss.item():.4f}")

print("Entrenamiento terminado ")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Precisión en MNIST: {100 * correct / total:}%")